# Generated by Django 5.0.1 on 2024-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_overview', '0003_remove_articleinfo_img1_articleinfo_img_path_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='start_and_finish_date',
            field=models.CharField(default=2001, max_length=50),
            preserve_default=False,
        ),
    ]
