# Generated by Django 5.0.1 on 2024-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_overview', '0004_articleinfo_start_and_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='status',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
