# Generated by Django 5.0.1 on 2024-01-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_overview', '0005_articleinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='article2',
            field=models.TextField(),
        ),
    ]
