# Generated by Django 5.0.1 on 2024-01-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_overview', '0006_alter_articleinfo_article_alter_articleinfo_article2'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='project_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
