# Generated by Django 5.0.1 on 2024-01-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_overview', '0007_articleinfo_project_finish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='start_and_finish_date',
        ),
    ]
